### ISSUE TITLE
www.gamesradar.com 

### ISSUE THREAD

**Issue by SKEIDs** [Yuki2718/adblock2#3]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL:  https://www.gamesradar.com/goldenjoystickawards/

### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![image](https://i.postimg.cc/Dz8BjWBK/xcvb0sfdvg.png)
</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version: Win11 22H2
- Browser and version:  GoogleChrome 119.0.6034.6
- AdGuard or uBlock Origin version: AdGuard web extension 4.2.168

### Filters (mandatory) / 使用フィルタ（必須）

AdGuard Japanese filter Plus

### Notes / その他有用な情報

Target element is this `class="ad-unit"`.

I think this issue occurred by this rule.
`#@#.ad-unit`

https://github.com/Yuki2718/adblock2/blob/a13347b60a60272bc2fec8c18aa825422e246b20/japanese/jpfp-ag.txt#L204C1-L204C12

**Comment by Yuki2718** [comment]
This is weired, in theory should be hidden by `~lamire.jp##.ad-unit:not(.text-ad):not(:empty):not(.textads)`. Need investigation.

**Comment by SKEIDs** [comment]
Sorry if this is my problem.

**Comment by Yuki2718** [comment]
I can reproduce by myself, but am suspecting a bug in AdGuard. Before opening an issue, I have to narrow down the condition it happens.

**Comment by SKEIDs** [comment]
> but am suspecting a bug in AdGuard. 

I see. I'm not sure if I can be of help, but I'll also look into it.

**Comment by SKEIDs** [comment]
I have researched this issue to the best of my ability and would like to report my findings. 

As far as I have tried, it was caused by Easylist(EL) and Adguard Annoyances.
Also, there was a difference between Chrome and Firefox.

### Prerequisites
1. Only subscribe EL (and Adguard Annoyance).
2. Add `##.ad-unit:not(.text-ad):not(:empty):not(.textads)` and `#@#.ad-unit` to the user list.

### How to solve the issue
- Chrome
When I subscribed to EL and AdGuard Japanese filter Plus, the issue can be resolved by adding 
`@@||bordeaux.futurecdn.net/bordeaux.js$domain=gamesradar.com`
Furthermore, if I am also subscribed to Adguard Annoyances, adding 
`@@||cdn.privacy-mgmt.com$domain=gamesradar.com` 
↑ 
I think this rule can be made more specific, but I could not been able to adjust it well.


- Firefox
When I subscribed to EL and AdGuard Japanese filter Plus, in addition to `@@||bordeaux.futurecdn.net/bordeaux.js$domain=gamesradar.com` , I also need to add 
`gamesradar.com#@%#(function(o){function(a){return{get:function(){return a},set:b}}function b(){}function c(){throw"Adguard: stopped a script execution.";}var d={},e=a(function(a){a(!1)}),f={},g=EventTarget.prototype.addEventListener;o(d,{spid_control_callback:a(b),content_control_callback:a(b),vid_control_callback:a(b)});o(f,{config:a(d),_setSpKey:{get:c,set:c},checkState:e,isAdBlocking:e,getSafeUri:a(function(a){return a}),pageChange:a(b),setupSmartBeacons:a(b)});Object.defineProperty(window,"sp",a(f));EventTarget.prototype.addEventListener=function(a){"sp.blocking"!=a&&"sp.not_blocking"!=a&&g.apply(this,arguments)}})(Object.defineProperties);`.
When subscribed to Adguard Annoyances is the same as for Chrome.

I hope this information is helpful. 

P.S.
I apologise if I have not explained it enough. If necessary, I can add an explain in Japanese.

**Comment by Yuki2718** [comment]
@SKEIDs Thank you for taking time, and sorry for the delay to fix the issue. Now I checked thoroughly and found it's not a bug but my lookover. Will fix soon.

**Comment by SKEIDs** [comment]
Excuse me, this is a completely different topic.
I think this is an error. Could you please take a look? And could you please fix stealthily it if you don't mind?
ttps://github.com/easylist/easylist/commit/469733066a7659286ea856006a4e4f65062e3f8a#comments

**Comment by Yuki2718** [comment]
Thanks, done.
