### ISSUE TITLE
Unintentional Blocking of DeepL Translation Pop-up ( `deepl-inline-trigger` Tag) (example.com)

### ISSUE THREAD

**Issue by rsuwa** [Yuki2718/adblock2#4]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

<https://example.com/>

Full URL / 完全なURL: <https://example.com/>

#### Problem:

The current AdGuard Japanese filter Plus filter:

```css
##div[style*="z-index: 2147483647;"][style*="top: 0px; left: 0px;"][style*="position:"]
```
unintentionally hides elements utilized by the DeepL extension, impacting its functionality. Specifically, it interferes with elements enclosed in `<deepl-inline-trigger></deepl-inline-trigger>`, which use the same `z-index` style, making them disappear when the filter is applied.

#### Impact:

Users employing the DeepL extension for translation purposes may experience disruptive behavior and might be unable to use the extension effectively with the filter enabled.

#### Proposed Solution:

A refinement of the filter, aimed at specifically targeting the undesired elements while preserving those related to DeepL, has been experimented with and found effective in preliminary testing:
```css
##body > div[style*="z-index: 2147483647;"][style*="top: 0px; left: 0px;"][style*="position:"]
```
This selector employs the direct child combinator (`>`) to restrict the filter's effect to `div` elements directly under the `body` tag, potentially reducing unintentional hiding of nested DeepL elements. Further testing and validation across various websites and scenarios would be beneficial.

### Steps to Reproduce:

1. Install and enable the DeepL browser extension.
    - Firefox: https://addons.mozilla.org/en-US/firefox/addon/deepl-translate/
    - Chromium: https://chrome.google.com/webstore/detail/deepl-translate-reading-w/cofdbpoegempjloogbagkncekinflcnj
3. Navigate to a webpage where you'd like to translate some text.
4. Select a text segment that you'd like to translate.
5. Notice that the DeepL pop-up (utilizing the deepl-inline-trigger tag) which should appear at the bottom right of the selected text is being blocked.

### Screenshot(s) / スクリーンショット

<details><summary>Correct behavior:</summary>

![image](https://i.gyazo.com/0a56d9ad1824a7c2da4eccfb75434dd7.gif)
</details>

<details><summary>Incorrect behavior:</summary>

![image](https://i.gyazo.com/eb0dc5729f1d2035d436669f6abe432a.gif)
</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン: macOS Ventura 13.6
- Browser and version / ブラウザの種類とバージョン: Firefox 118.0.2
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: uBlock Origin 1.52.2

### Filters (mandatory) / 使用フィルタ（必須）

```
listset (total-discarded, last-updated):
 added:
  https://abp.oisd.nl/: 206954-49818, 3h.5m
  https://get.letsblock.it/list/c6c363ab-28ec-4d56-aae3-dbcc8eed8d58.txt: 126-86, 3h.5m
  https://malware-filter.gitlab.io/pup-filter/pup-filter.txt: 189-0, 3h.5m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/ClearURLs%20for%20uBo/clear_urls_uboified.txt: 712-8, 3h.5m
  https://raw.githubusercontent.com/DandelionSprout/adfilt/master/LegitimateURLShortener.txt: 2495-77, 3h.5m
  https://raw.githubusercontent.com/Yuki2718/adblock2/main/japanese/jpf-plus.txt: 760-32, never
  https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/ichigo_filter.txt: 1588-65, 3h.5m
  https://raw.githubusercontent.com/eEIi0A5L/adblock_filter/master/kame_filter.txt: 153-0, 3h.5m
  https://raw.githubusercontent.com/quenhus/uBlock-Origin-dev-filter/main/dist/all_search_engines/global.txt: 7010-0, 3h.5m
  https://www.i-dont-care-about-cookies.eu/abp/: 25832-19, 3h.6m
  adguard-generic: 78392-6817, 3h.6m
  adguard-mobile: 8681-131, 3h.6m
  [21 lists not shown]: [too many]
 default:
  user-filters: 83-2, never
  ublock-filters: 35783-619, 3h.6m
  ublock-badware: 7213-9, 3h.6m
  ublock-privacy: 589-49, 3h.5m
  ublock-unbreak: 2185-2, 3h.6m
  ublock-quick-fixes: 188-0, 3h.5m
  easylist: 71651-1188, 3h.6m
  easyprivacy: 33224-930, 3h.6m
  urlhaus-1: 10910-0, 3h.5m
  plowe-0: 3719-32, 3h.6m
  JPN-1: 13522-102, 3h.6m
```

**Comment by Yuki2718** [comment]
Thank you, though it was not reproduced as z-index on my end is slightly different, I see false positive is very likely to happen. Adjusted as you suggested.

**Comment by lisansas** [comment]
##body > div[style*="z-index: 2147483647;"][style*="top: 0px; left: 0px;"][style*="position:"]
↑
This rule block all Bitwarden extension‘s ask to save password nofitication in Firefox.

**Comment by Yuki2718** [comment]
> ##body > div[style*="z-index: 2147483647;"][style*="top: 0px; left: 0px;"][style*="position:"] ↑ This rule block all Bitwarden extension‘s ask to save password nofitication in Firefox.

I added the Bitwarden extension to Firefox and created an account, logged in, and logged into gmail but it didn't show notification to save password. How to reproduce that, or can you share the DOM?

**Comment by lisansas** [comment]
> > ##body > div[style*="z-index: 2147483647;"][style*="top: 0px; left: 0px;"][style*="position:"] ↑ This rule block all Bitwarden extension‘s ask to save password nofitication in Firefox.
> 
> I added the Bitwarden extension to Firefox and created an account, logged in, and logged into gmail but it didn't show notification to save password. How to reproduce that, or can you share the DOM?

Thanks for you reply.

You can test in https://fill.dev/form/login-simple

**Comment by Yuki2718** [comment]
Thanks, added a workaround. Maybe I have to refine these rules to mitigate popups when I find time, but that should work at least for the reported breakage.
