### ISSUE TITLE
jin115.com

### ISSUE THREAD

**Issue by reindex-ot** [Yuki2718/adblock2#6]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL: [jin115.com](jin115.com)

### Describe the issue (mandatory) / 何が問題か説明してください（必須）
e8e2063b.xyz のバナー広告が表示される

### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![Screenshot_2024-08-03-06-45-41-500_com android chrome](https://github.com/user-attachments/assets/9b4e47ef-e77b-434a-bc5c-8ce6eb3814a5)

</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン: Xiaomi Hyper OS v1.0.5.0 (Android 14)
- Browser and version / ブラウザの種類とバージョン: Google Chrome : 127.0.6533.85
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: AdGuard v4.6.1

### Filters (mandatory) / 使用フィルタ（必須）

- AdGuardベースフィルタ
- AdGuardモバイル広告フィルタ
- AdGuard URL 追跡防止フィルタ
- AdGuard 迷惑要素フィルタ
- AdGuard DNS フィルタ
- AdGuard Japanese filter Plus

### Notes / その他有用な情報
i-mobile Ad Networkの広告に関係するようです。

**Comment by Yuki2718** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/185247
（`https://x.com/Yuki27183/status/1819349168034664740`）だと思うのですが、フィルター更新とブラウザのキャッシュ削除をしてもまだ出ますか？

**Comment by reindex-ot** [comment]
キャッシュの削除、AdGuardの再起動、フィルタの更新をやりましたが表示されます。microShieldのユーザースクリプトもインストール済みの環境です。

**Comment by Yuki2718** [comment]
私の環境（Android14, AdGuard v4.6.1）では再現しないんですよね。AdGuardのバグなどの可能性を切り分けるため、FirefoxかKiwiにuBlock OriginかAdGuard拡張を入れても出るかお試しいただけませんか？

**Comment by reindex-ot** [comment]
遅れて申し訳ありません。
KiwiでAdGuardの拡張を入れて確かめてみたところ、バナーは遮断されていました。
フィルタ、スクリプトの更新後にChromeはhtml-load.comがブロックされているエラーが出るようになりました。
![Screenshot_2024-08-13-23-13-23-667_com android chrome-edit](https://github.com/user-attachments/assets/ce448cf4-fce8-44d1-b5d0-4eb9620f9159)

**Comment by Yuki2718** [comment]
それが出るのはcspフィルタとHTMLフィルタがどちらも効いていないということだと思われるのですが、原因がよくわかりません。microShieldと干渉でもしているのかと思い確認しましたが、少なくともこちらではその線もなさそうでした。

**Comment by reindex-ot** [comment]
microShieldが対応したのかエラーが出なくなりました。
