### ISSUE TITLE
https://www.twitch.tv/

### ISSUE THREAD

**Issue by eitimiyabi** [Yuki2718/adblock2#7]
### URL(s) where the issue occurs (mandatory) / 問題のURL（必須）

Full URL / 完全なURL: https://www.twitch.tv/

### Describe the issue (mandatory) / 何が問題か説明してください（必須）
twitchの配信を開くと最初に出てくる広告動画が流れる

### Screenshot(s) / スクリーンショット

<details><summary>Screenshot:</summary>

![image](%screenshot_url%)
</details>

### Versions (mandatory) / バージョン情報（必須）

- Operating system and version / OSの種類とバージョン: Windows11 23H2
- Browser and version / ブラウザの種類とバージョン: chrome 127.0.6533.100（Official Build） （64 ビット）
- AdGuard or uBlock Origin version / AdGuardないしuBlock Originのバージョン: 1.59.0

### Filters (mandatory) / 使用フィルタ（必須）

・　AdGuard Japanese filter Plus

**Comment by Yuki2718** [comment]
Twitchの動画広告はフィルターではブロックできません。
https://github.com/pixeltris/TwitchAdSolutions
をよく読み、`twitch.tv##+js(twitch-videoad)`の追加と`userResourcesLocation`の設定を行うか、任意のスクリプトマネジャーで`vaft`を使う、もしくは`TTV LOL PRO`などの専用拡張機能を使ってください。
